namespace Az204AiLearningAssistant.Api.Application;

using Az204AiLearningAssistant.Api.Contracts;
using Az204AiLearningAssistant.Api.Validation;

public sealed class AiLearningAssistantService : IAiLearningAssistantService
{
    private readonly ITopicAllowlistValidator _topicAllowlistValidator;
    private readonly IJsonSchemaValidator _jsonSchemaValidator;
    private readonly IAnswerSelfCheckService _answerSelfCheckService;

    public AiLearningAssistantService(
        ITopicAllowlistValidator topicAllowlistValidator,
        IJsonSchemaValidator jsonSchemaValidator,
        IAnswerSelfCheckService answerSelfCheckService)
    {
        _topicAllowlistValidator = topicAllowlistValidator;
        _jsonSchemaValidator = jsonSchemaValidator;
        _answerSelfCheckService = answerSelfCheckService;
    }

    public async Task<GenerateQuizResponse> GenerateQuizAsync(GenerateQuizRequest request, CancellationToken cancellationToken = default)
    {
        if (!_topicAllowlistValidator.IsAllowedTopic(request.Topic))
        {
            throw new InvalidOperationException("Requested topic is not allowed.");
        }

        _jsonSchemaValidator.ValidateGenerateQuizRequest(request);

        // TODO: Call Azure OpenAI to generate quiz content.

        // TODO: Use _answerSelfCheckService to perform a confidence/self-check on generated quiz.

        // Placeholder response for initial skeleton.
        await Task.CompletedTask;

        return new GenerateQuizResponse
        {
            Topic = request.Topic,
            Questions = []
        };
    }

    public async Task<ExplainAnswerResponse> ExplainAnswerAsync(ExplainAnswerRequest request, CancellationToken cancellationToken = default)
    {
        if (!_topicAllowlistValidator.IsAllowedTopic(request.Topic))
        {
            throw new InvalidOperationException("Requested topic is not allowed.");
        }

        _jsonSchemaValidator.ValidateExplainAnswerRequest(request);

        // TODO: Call Azure OpenAI to explain the answer.

        // TODO: Use _answerSelfCheckService to perform a confidence/self-check on the explanation.

        await Task.CompletedTask;

        return new ExplainAnswerResponse
        {
            Topic = request.Topic,
            Explanation = "Explanation will be generated by Azure OpenAI in a future step.",
            Confidence = null
        };
    }
}

